DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE url_checks (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status_code INTEGER,
    title VARCHAR(128) NULL,
    h1 VARCHAR(128) NULL,
    description VARCHAR(512) NULL,
    url_id INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (url_id) REFERENCES urls(id)
);