DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

INSERT INTO urls (name) VALUES ('http://popolam.money');